source 'https://rubygems.org/'
ruby '~>3.3.0'

gem 'bcrypt'
gem 'rack'
gem 'rackup'
gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-reloader'
gem 'slim'
gem 'sqlite3'
gem 'yard'
gem 'yard-sinatra', git: 'https://github.com/chrisb/yard-sinatra'